// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqHwYuR1Mck-aKGlA6g_DN5iAhJ9zwzZg',
    appId: '1:1062441251095:web:f96b1a399ee59cb3e0c752',
    messagingSenderId: '1062441251095',
    projectId: 'chat-flutter-2ff60',
    authDomain: 'chat-flutter-2ff60.firebaseapp.com',
    storageBucket: 'chat-flutter-2ff60.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoKPjuB-W9YH7yLq8WvsPqdTtALV1fd6w',
    appId: '1:1062441251095:android:16aa3f774b6cb248e0c752',
    messagingSenderId: '1062441251095',
    projectId: 'chat-flutter-2ff60',
    storageBucket: 'chat-flutter-2ff60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrsQWMhoigKUhN_nuCPQO74rvArxP4Yk4',
    appId: '1:1062441251095:ios:a9396941a12ae405e0c752',
    messagingSenderId: '1062441251095',
    projectId: 'chat-flutter-2ff60',
    storageBucket: 'chat-flutter-2ff60.appspot.com',
    iosClientId: '1062441251095-qc4947iq5ab2diegu2951qd5gf816h4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrsQWMhoigKUhN_nuCPQO74rvArxP4Yk4',
    appId: '1:1062441251095:ios:a9396941a12ae405e0c752',
    messagingSenderId: '1062441251095',
    projectId: 'chat-flutter-2ff60',
    storageBucket: 'chat-flutter-2ff60.appspot.com',
    iosClientId: '1062441251095-qc4947iq5ab2diegu2951qd5gf816h4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
